# Generated by Django 3.2.9 on 2021-11-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Radius_mean', models.CharField(max_length=100, null=True)),
                ('Texture_mean', models.CharField(max_length=100, null=True)),
                ('Perimeter_mean', models.CharField(max_length=100, null=True)),
                ('Area_mean', models.CharField(max_length=100, null=True)),
                ('Smoothness_mean', models.CharField(max_length=100, null=True)),
                ('Compactness_mean', models.CharField(max_length=100, null=True)),
                ('Concavity_mean', models.CharField(max_length=100, null=True)),
                ('Concave_points_mean', models.CharField(max_length=100, null=True)),
                ('Symmetry_mean', models.CharField(max_length=100, null=True)),
                ('Fractal_dimension_mean', models.CharField(max_length=100, null=True)),
                ('Radius_se', models.CharField(max_length=100, null=True)),
                ('Texture_se', models.CharField(max_length=100, null=True)),
                ('Perimeter_se', models.CharField(max_length=100, null=True)),
                ('Area_se', models.CharField(max_length=100, null=True)),
                ('Smoothness_se', models.CharField(max_length=100, null=True)),
                ('Compactness_se', models.CharField(max_length=100, null=True)),
                ('Concavity_se', models.CharField(max_length=100, null=True)),
                ('Concave_points_se', models.CharField(max_length=100, null=True)),
                ('Symmetry_se', models.CharField(max_length=100, null=True)),
                ('Fractal_dimension_se', models.CharField(max_length=100, null=True)),
                ('Radius_worst', models.CharField(max_length=100, null=True)),
                ('Texture_worst', models.CharField(max_length=100, null=True)),
                ('Perimeter_worst', models.CharField(max_length=100, null=True)),
                ('Area_worst', models.CharField(max_length=100, null=True)),
                ('Smoothness_worst', models.CharField(max_length=100, null=True)),
                ('Compactness_worst', models.CharField(max_length=100, null=True)),
                ('Concavity_worst', models.CharField(max_length=100, null=True)),
                ('Concave_points_worst', models.CharField(max_length=100, null=True)),
                ('Symmetry_worst', models.CharField(max_length=100, null=True)),
                ('Fractal_dimension_worst', models.CharField(max_length=100, null=True)),
                ('predictions', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
