# Generated by Django 3.2.9 on 2021-11-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Pasien', models.CharField(max_length=100)),
                ('Tgl_Periksa', models.DateField(null=True)),
                ('Diagnosis', models.CharField(max_length=40)),
                ('Radius_mean', models.IntegerField(null=True)),
                ('Texture_mean', models.IntegerField(null=True)),
                ('Perimeter_mean', models.IntegerField(null=True)),
                ('Area_mean', models.IntegerField(null=True)),
                ('Smoothness_mean', models.IntegerField(null=True)),
                ('Compactness_mean', models.IntegerField(null=True)),
                ('Concavity_mean', models.IntegerField(null=True)),
                ('Concave_points_mean', models.IntegerField(null=True)),
                ('Symmetry_mean', models.IntegerField(null=True)),
                ('Fractal_dimension_mean', models.IntegerField(null=True)),
                ('Radius_se', models.IntegerField(null=True)),
                ('Texture_se', models.IntegerField(null=True)),
                ('Perimeter_se', models.IntegerField(null=True)),
                ('Area_se', models.IntegerField(null=True)),
                ('Smoothness_se', models.IntegerField(null=True)),
                ('Compactness_se', models.IntegerField(null=True)),
                ('Concavity_se', models.IntegerField(null=True)),
                ('Concave_points_se', models.IntegerField(null=True)),
                ('Symmetry_se', models.IntegerField(null=True)),
                ('Fractal_dimension_se', models.IntegerField(null=True)),
                ('Radius_worst', models.IntegerField(null=True)),
                ('Texture_worst', models.IntegerField(null=True)),
                ('Perimeter_worst', models.IntegerField(null=True)),
                ('Area_worst', models.IntegerField(null=True)),
                ('Smoothness_worst', models.IntegerField(null=True)),
                ('Compactness_worst', models.IntegerField(null=True)),
                ('Concavity_worst', models.IntegerField(null=True)),
                ('Concave_points_worst', models.IntegerField(null=True)),
                ('Symmetry_worst', models.IntegerField(null=True)),
                ('Fractal_dimension_worst', models.IntegerField(null=True)),
            ],
        ),
    ]
